package generate

import (
	"strings"

	"github.com/vinayaksonthalia/telelens/internal/findings"
)

// CastingPatch wraps the generated processor fragment as a Foundry
// casting.yaml `ingester.config.data` block — the Foundry-native application
// surface: a human merges this into casting.yaml and runs
// `foundryctl forge && foundryctl cast` to roll the collector.
func CastingPatch(fs []findings.Finding) string {
	fragment := OtelcolFragment(fs)

	var b strings.Builder
	b.WriteString("# Generated by telelens — Foundry casting patch variant.\n")
	b.WriteString("# Merge the block below into your casting.yaml, then run:\n")
	b.WriteString("#   foundryctl forge -f casting.yaml && foundryctl cast -f casting.yaml\n")
	b.WriteString("# (TELELENS never applies this itself: profilers are read-only.)\n")
	b.WriteString("spec:\n")
	b.WriteString("  ingester:\n")
	b.WriteString("    config:\n")
	b.WriteString("      data:\n")
	for _, line := range strings.Split(strings.TrimRight(fragment, "\n"), "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("        " + line + "\n")
	}
	return b.String()
}
