// Package generate renders TELELENS's only outputs that touch disk: the
// annotated OTel Collector config fragment, its Foundry casting.yaml patch
// variant, and the Waste Report (markdown + JSON). Generators never apply
// anything: a human reviews the files and runs `foundryctl cast`.
package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/vinayaksonthalia/telelens/internal/findings"
)

// OtelcolFragment renders a valid OpenTelemetry Collector config fragment
// from the findings' fix hints. Every processor block is annotated with the
// finding it addresses and its projected saving, so the fragment doubles as
// its own review document.
func OtelcolFragment(fs []findings.Finding) string {
	var b strings.Builder
	b.WriteString("# Generated by telelens — review, then merge into your collector config.\n")
	b.WriteString("# Apply via Foundry: see casting-patch.yaml next to this file.\n")
	b.WriteString("# Profilers are read-only; nothing is applied until YOU run `foundryctl cast`.\n")
	b.WriteString("processors:\n")

	var processors []string // for the pipelines hint

	// tail_sampling (at most one; hints are merged).
	if f, ok := firstFix(fs, findings.FixTailSampling); ok {
		h := f.Fix
		b.WriteString(annotate(f, 2))
		fmt.Fprintf(&b, `  tail_sampling:
    decision_wait: 10s
    num_traces: 50000
    policies:
      - name: keep-errors            # %[1]s: never sampled away
        type: status_code
        status_code: { status_codes: [ERROR] }
      - name: keep-slow              # %[1]s: latency outliers always kept
        type: latency
        latency: { threshold_ms: %[2]s }
      - name: sample-boring-successes # %[1]s
        type: probabilistic
        probabilistic: { sampling_percentage: %[3]s }
`, f.ID,
			fmt.Sprintf("%.0f", h.LatencyThresholdMS),
			fmt.Sprintf("%g", h.SamplingPct))
		processors = append(processors, "tail_sampling")
	}

	// filter/logs per service.
	for _, f := range fixes(fs, findings.FixFilterLogs) {
		name := "filter/logs_" + sanitize(f.Fix.Service) + "_below_" + strings.ToLower(f.Fix.MaxSeverity)
		b.WriteString(annotate(f, 2))
		fmt.Fprintf(&b, `  %s:
    error_mode: ignore
    logs:
      log_record:
        - 'resource.attributes["service.name"] == %q and severity_number < SEVERITY_NUMBER_%s'
`, name, f.Fix.Service, strings.ToUpper(f.Fix.MaxSeverity))
		processors = append(processors, name)
	}

	// transform: attribute drops + truncations for traces.
	dropAttrs := fixes(fs, findings.FixDropAttribute)
	truncAttrs := fixes(fs, findings.FixTruncateAttribute)
	if len(dropAttrs)+len(truncAttrs) > 0 {
		b.WriteString("  transform/span_attribute_diet:\n")
		b.WriteString("    error_mode: ignore\n")
		b.WriteString("    trace_statements:\n")
		b.WriteString("      - context: span\n")
		b.WriteString("        statements:\n")
		uniqDrops, alsoDrops := dedupeFixes(dropAttrs, func(f findings.Finding) string {
			return f.Fix.Attribute
		})
		for _, f := range uniqDrops {
			fmt.Fprintf(&b, "          # %s%s: %s (saves ~%s)\n",
				f.ID, alsoNote(alsoDrops[f.Fix.Attribute]), f.Title, gbmo(f))
			fmt.Fprintf(&b, "          - delete_key(attributes, %q)\n", f.Fix.Attribute)
		}
		for _, f := range truncAttrs {
			fmt.Fprintf(&b, "          # %s: %s (saves ~%s)\n", f.ID, f.Title, gbmo(f))
			fmt.Fprintf(&b, "          - set(attributes[%q], Substring(attributes[%q], 0, %d)) where Len(attributes[%q]) > %d\n",
				f.Fix.Attribute, f.Fix.Attribute, f.Fix.TruncateBytes, f.Fix.Attribute, f.Fix.TruncateBytes)
		}
		processors = append(processors, "transform/span_attribute_diet")
	}

	// transform: metric label bombs. Two profilers can independently ask for
	// the same (label, metric) pair — the metrics cardinality profiler as a
	// series bomb, the ecosystem profiler as a structurally unbounded ID — so
	// emit one OTTL statement per pair and credit every finding that wanted it.
	if bombs := fixes(fs, findings.FixDropMetricLabel); len(bombs) > 0 {
		b.WriteString("  transform/defuse_label_bombs:\n")
		b.WriteString("    error_mode: ignore\n")
		b.WriteString("    metric_statements:\n")
		b.WriteString("      - context: datapoint\n")
		b.WriteString("        statements:\n")
		uniqBombs, alsoBombs := dedupeFixes(bombs, labelBombKey)
		for _, f := range uniqBombs {
			fmt.Fprintf(&b, "          # %s%s: %s (saves ~%s)\n",
				f.ID, alsoNote(alsoBombs[labelBombKey(f)]), f.Title, gbmo(f))
			fmt.Fprintf(&b, "          - delete_key(attributes, %q) where metric.name == %q\n",
				f.Fix.Attribute, f.Fix.Metric)
		}
		processors = append(processors, "transform/defuse_label_bombs")
	}

	// filter: orphan metrics. This block ships COMMENTED-OUT: "unread" is
	// derived from SigNoz dashboards + alert rules only, so a metric read by
	// anything else (an external Prometheus, a sibling pipeline) would be
	// silently dropped if the block were live. Platform-consumed prefixes
	// (signoz_*, otelcol_*, otel.sdk.*) are already excluded at the profiler,
	// but the review step stays mandatory.
	if orphans := fixes(fs, findings.FixDropMetric); len(orphans) > 0 {
		b.WriteString("  # ──────────────────────────────────────────────────────────────────\n")
		b.WriteString("  # REVIEW BEFORE ENABLING — this block is deliberately commented out.\n")
		b.WriteString("  # \"Unread\" means: referenced by no SigNoz dashboard or alert rule.\n")
		b.WriteString("  # telelens cannot see external consumers (federated Prometheus,\n")
		b.WriteString("  # other pipelines). Verify each metric really has no reader, delete\n")
		b.WriteString("  # the lines you must keep, then uncomment the block.\n")
		b.WriteString("  # ──────────────────────────────────────────────────────────────────\n")
		b.WriteString("  # filter/drop_unread_metrics:\n")
		b.WriteString("  #   error_mode: ignore\n")
		b.WriteString("  #   metrics:\n")
		b.WriteString("  #     exclude:\n")
		b.WriteString("  #       match_type: strict\n")
		b.WriteString("  #       metric_names:\n")
		for _, f := range orphans {
			fmt.Fprintf(&b, "  #         - %s  # %s: saves ~%s\n", f.Fix.Metric, f.ID, gbmo(f))
			for _, m := range f.Fix.Metrics {
				fmt.Fprintf(&b, "  #         - %s  # %s\n", m, f.ID)
			}
		}
		processors = append(processors, "filter/drop_unread_metrics")
	}

	// Pipeline placement hint.
	b.WriteString("\n# Suggested pipeline placement (merge with your existing pipelines):\n")
	b.WriteString("# service:\n#   pipelines:\n")
	if hasAny(processors, "tail_sampling", "transform/span_attribute_diet") {
		if hasAny(processors, "tail_sampling") {
			// The M4 live run proved this the hard way: a default SigNoz
			// ingester computes RED metrics from the traces pipeline, and
			// sampling before spanmetrics silently corrupts them.
			b.WriteString("#     # IMPORTANT: keep signozspanmetrics BEFORE tail_sampling so RED\n")
			b.WriteString("#     # metrics see 100% of spans (sampling first silently corrupts them).\n")
		}
		b.WriteString("#     traces:  processors: [" + joinMatching(processors, "tail_sampling", "transform/span_attribute_diet") + ", batch]\n")
	}
	if logsProcs := joinPrefixed(processors, "filter/logs_"); logsProcs != "" {
		b.WriteString("#     logs:    processors: [" + logsProcs + ", batch]\n")
	}
	if metricProcs := joinMatching(processors, "transform/defuse_label_bombs", "filter/drop_unread_metrics"); metricProcs != "" {
		b.WriteString("#     metrics: processors: [" + metricProcs + ", batch]\n")
		if hasAny(processors, "filter/drop_unread_metrics") {
			b.WriteString("#     # (filter/drop_unread_metrics is commented out above — include it\n")
			b.WriteString("#     #  here only after reviewing and uncommenting the block.)\n")
		}
	}
	return b.String()
}

// ---- helpers ----

func annotate(f findings.Finding, indent int) string {
	pad := strings.Repeat(" ", indent)
	return fmt.Sprintf("%s# %s: %s (saves ~%s)\n", pad, f.ID, f.Title, gbmo(f))
}

func gbmo(f findings.Finding) string {
	if f.Directional() {
		return "n/a (directional)"
	}
	return fmt.Sprintf("%.1f GB/mo ≈ $%.2f/mo", f.EstGBPerMonth, f.EstUSDPerMonth)
}

func firstFix(fs []findings.Finding, kind findings.FixKind) (findings.Finding, bool) {
	for _, f := range fs {
		if f.Fix.Kind == kind {
			return f, true
		}
	}
	return findings.Finding{}, false
}

func fixes(fs []findings.Finding, kind findings.FixKind) []findings.Finding {
	var out []findings.Finding
	for _, f := range fs {
		if f.Fix.Kind == kind {
			out = append(out, f)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// labelBombKey identifies the OTTL statement a drop-metric-label fix produces:
// the same (label, metric) pair yields a byte-identical statement.
func labelBombKey(f findings.Finding) string {
	return f.Fix.Attribute + "\x00" + f.Fix.Metric
}

// dedupeFixes keeps the first finding per statement key, in order, and returns
// the IDs of the later findings that asked for that same statement. Emitting a
// duplicate OTTL line is not wrong — delete_key is idempotent — but a config a
// human is asked to review must not repeat itself.
func dedupeFixes(fs []findings.Finding, key func(findings.Finding) string) ([]findings.Finding, map[string][]string) {
	var uniq []findings.Finding
	seen := map[string]bool{}
	also := map[string][]string{}
	for _, f := range fs {
		k := key(f)
		if seen[k] {
			also[k] = append(also[k], f.ID)
			continue
		}
		seen[k] = true
		uniq = append(uniq, f)
	}
	return uniq, also
}

// alsoNote credits the extra findings that asked for an already-emitted line.
func alsoNote(ids []string) string {
	if len(ids) == 0 {
		return ""
	}
	return " (also " + strings.Join(ids, ", ") + ")"
}

func sanitize(s string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			return r
		case r >= 'A' && r <= 'Z':
			return r + ('a' - 'A')
		default:
			return '_'
		}
	}, s)
}

func hasAny(have []string, want ...string) bool { return joinMatching(have, want...) != "" }

func joinMatching(have []string, want ...string) string {
	var out []string
	for _, w := range want {
		for _, h := range have {
			if h == w {
				out = append(out, h)
			}
		}
	}
	return strings.Join(out, ", ")
}

func joinPrefixed(have []string, prefix string) string {
	var out []string
	for _, h := range have {
		if strings.HasPrefix(h, prefix) {
			out = append(out, h)
		}
	}
	return strings.Join(out, ", ")
}
